### ISSUE TITLE
Check the photodiode carefully! It should be TEMD6200FX01. Do not use TEMT6200FX01

### ISSUE THREAD

**Issue by tatthangvd** [strawlab/Miriam#3]
For our recent batch of components, Mouser sent us the wrong photodiode "TEMT6200FX01" instead of "TEMD6200FX01". I never expect it could happen and did not notice that "TEMT6200FX01" exist.
Better check the components carefully when receiving them.
Correct link:
https://www.mouser.de/ProductDetail/782-TEMD6200FX01

**Comment by astraw** [comment]
Thanks for the warning!
